kind: Service
apiVersion: v1
metadata:
  name: text-generation-webui
  namespace: text-gen
  labels:
    app: text-generation-webui
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: 5005-tcp
      protocol: TCP
      port: 5005
      targetPort: 5005
    - name: 7860-tcp
      protocol: TCP
      port: 7860
      targetPort: 7860
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: text-generation-webui
    deployment: text-generation-webui
